[colors.primary]
background = '#282828'
foreground = '#ddc7a1'

[colors.selection]
text = '#ddc7a1'
background = '#6a4f2d'

[colors.cursor]
text = '#282828'
cursor = '#d8a657'

[colors.normal]
black   = '#1b1b1b'
red     = '#f86155'
green   = '#6bd857'
yellow  = '#ffe257'
blue    = '#cd943a'
magenta = '#643d00'
cyan    = '#d8a657'
white   = '#e2dcd2'

[colors.bright]
black   = '#8c877f'
red     = '#ff958c'
green   = '#a5ff94'
yellow  = '#ffec94'
blue    = '#edbe74'
magenta = '#ffd594'
cyan    = '#ffe4ba'
white   = '#fffcf7'
